repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.svg$|^docs/image
  - repo: https://github.com/sirosen/texthooks
    rev: "0.6.7"
    hooks:
      - id: fix-smartquotes
        stages: [pre-commit]
      - id: fix-ligatures
        stages: [pre-commit]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Check Markdown files with markdownlint
        args: ["--config=.github/linters/.markdownlint.yaml", "-f"]
        stages: [pre-commit]
        exclude: ^\.github/.*$
        types: [markdown]
        files: \.(md|mdown|markdown)$
