site_name: Internal Docs for L4 Development
site_url: https://smucclaw.github.io/internal_docs/
nav:
  - Home: index.md
  - Historical Context (high-level): historical_context.md
  - The L4 System:
      - current_system/index.md
      - Notes on Codebase:
          - current_system/codebase/index.md
          - The Rule AST: current_system/codebase/rule-ast.md
  - For the Future:
      - Wishlist: future_aspirations.md
      - Misc Notes or Ideas: misc.md
  - Further Reading: further_reading.md
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.top
    - navigation.expand
    - navigation.path
    # - navigation.prune
    - navigation.instant
    - toc.follow
    - toc.integrate
